// Generated by Scripts/sync_playlist_sources.py
// Keep old Playlist* and Media* names as compatibility aliases while WebMedia* becomes canonical.

import Foundation

@available(*, deprecated, renamed: "DownloadedWebMediaArtifact")
public typealias DownloadedMediaArtifact = DownloadedWebMediaArtifact

@available(*, deprecated, renamed: "WebMediaHLSAssetDownloader")
public typealias HLSAssetDownloader = WebMediaHLSAssetDownloader

@available(*, deprecated, renamed: "WebMediaHLSAssetDownloading")
public typealias HLSAssetDownloading = WebMediaHLSAssetDownloading

@available(*, deprecated, renamed: "WebMediaArtifactDownloading")
public typealias MediaArtifactDownloading = WebMediaArtifactDownloading

@available(*, deprecated, renamed: "WebMediaAssetDownloader")
public typealias MediaAssetDownloader = WebMediaAssetDownloader

@available(*, deprecated, renamed: "WebMediaBuiltScriptSet")
public typealias MediaBuiltScriptSet = WebMediaBuiltScriptSet

@available(*, deprecated, renamed: "WebMediaCandidateSelector")
public typealias MediaCandidateSelector = WebMediaCandidateSelector

@available(*, deprecated, renamed: "WebMediaCaptureCandidate")
public typealias MediaCaptureCandidate = WebMediaCaptureCandidate

@available(*, deprecated, renamed: "WebMediaCaptureCandidateSelector")
public typealias MediaCaptureCandidateSelector = WebMediaCaptureCandidateSelector

@available(*, deprecated, renamed: "WebMediaCaptureDownloadProgress")
public typealias MediaCaptureDownloadProgress = WebMediaCaptureDownloadProgress

@available(*, deprecated, renamed: "WebMediaCaptureDownloadedMedia")
public typealias MediaCaptureDownloadedMedia = WebMediaCaptureDownloadedMedia

@available(*, deprecated, renamed: "WebMediaCaptureDownloader")
public typealias MediaCaptureDownloader = WebMediaCaptureDownloader

@available(*, deprecated, renamed: "WebMediaCaptureLibrary")
public typealias MediaCaptureLibrary = WebMediaCaptureLibrary

@available(*, deprecated, renamed: "WebMediaCaptureMediaKind")
public typealias MediaCaptureMediaKind = WebMediaCaptureMediaKind

@available(*, deprecated, renamed: "WebMediaCaptureMessage")
public typealias MediaCaptureMessage = WebMediaCaptureMessage

@available(*, deprecated, renamed: "WebMediaCaptureMessageDecoder")
public typealias MediaCaptureMessageDecoder = WebMediaCaptureMessageDecoder

@available(*, deprecated, renamed: "WebMediaCapturePlaybackEvent")
public typealias MediaCapturePlaybackEvent = WebMediaCapturePlaybackEvent

@available(*, deprecated, renamed: "WebMediaCapturePlaybackEventName")
public typealias MediaCapturePlaybackEventName = WebMediaCapturePlaybackEventName

@available(*, deprecated, renamed: "WebMediaCapturePlaybackKind")
public typealias MediaCapturePlaybackKind = WebMediaCapturePlaybackKind

@available(*, deprecated, renamed: "WebMediaCapturePlaybackPresentationMode")
public typealias MediaCapturePlaybackPresentationMode = WebMediaCapturePlaybackPresentationMode

@available(*, deprecated, renamed: "WebMediaCapturePlaybackSnapshot")
public typealias MediaCapturePlaybackSnapshot = WebMediaCapturePlaybackSnapshot

@available(*, deprecated, renamed: "WebMediaCaptureReadyState")
public typealias MediaCaptureReadyState = WebMediaCaptureReadyState

@available(*, deprecated, renamed: "WebMediaCaptureRequestContext")
public typealias MediaCaptureRequestContext = WebMediaCaptureRequestContext

@available(*, deprecated, renamed: "WebMediaCaptureRequestContextBuilder")
public typealias MediaCaptureRequestContextBuilder = WebMediaCaptureRequestContextBuilder

@available(*, deprecated, renamed: "WebMediaCaptureResolutionMethod")
public typealias MediaCaptureResolutionMethod = WebMediaCaptureResolutionMethod

@available(*, deprecated, renamed: "WebMediaCaptureResolvedMedia")
public typealias MediaCaptureResolvedMedia = WebMediaCaptureResolvedMedia

@available(*, deprecated, renamed: "WebMediaCaptureRetentionPolicy")
public typealias MediaCaptureRetentionPolicy = WebMediaCaptureRetentionPolicy

@available(*, deprecated, renamed: "WebMediaCaptureScriptConfiguration")
public typealias MediaCaptureScriptConfiguration = WebMediaCaptureScriptConfiguration

@available(*, deprecated, renamed: "WebMediaCaptureStorageScope")
public typealias MediaCaptureStorageScope = WebMediaCaptureStorageScope

@available(*, deprecated, renamed: "WebMediaCaptureStoredMedia")
public typealias MediaCaptureStoredMedia = WebMediaCaptureStoredMedia

@available(*, deprecated, renamed: "WebMediaCaptureWebScriptSet")
public typealias MediaCaptureWebScriptSet = WebMediaCaptureWebScriptSet

@available(*, deprecated, renamed: "WebMediaCaptureWebScripts")
public typealias MediaCaptureWebScripts = WebMediaCaptureWebScripts

@available(*, deprecated, renamed: "WebMediaContainerKind")
public typealias MediaContainerKind = WebMediaContainerKind

@available(*, deprecated, renamed: "WebMediaDownloadEvent")
public typealias MediaDownloadEvent = WebMediaDownloadEvent

@available(*, deprecated, renamed: "WebMediaDownloadEventKind")
public typealias MediaDownloadEventKind = WebMediaDownloadEventKind

@available(*, deprecated, renamed: "WebMediaDownloadProgress")
public typealias MediaDownloadProgress = WebMediaDownloadProgress

@available(*, deprecated, renamed: "WebMediaDownloadRecord")
public typealias MediaDownloadRecord = WebMediaDownloadRecord

@available(*, deprecated, renamed: "WebMediaDownloadState")
public typealias MediaDownloadState = WebMediaDownloadState

@available(*, deprecated, renamed: "WebMediaInfo")
public typealias MediaInfo = WebMediaInfo

@available(*, deprecated, renamed: "WebMediaKind")
public typealias MediaKind = WebMediaKind

@available(*, deprecated, renamed: "WebMediaLibrary")
public typealias MediaLibrary = WebMediaLibrary

@available(*, deprecated, renamed: "WebMediaMimeTypeDetector")
public typealias MediaMimeTypeDetector = WebMediaMimeTypeDetector

@available(*, deprecated, renamed: "WebMediaPlaybackEvent")
public typealias MediaPlaybackEvent = WebMediaPlaybackEvent

@available(*, deprecated, renamed: "WebMediaPlaybackEventName")
public typealias MediaPlaybackEventName = WebMediaPlaybackEventName

@available(*, deprecated, renamed: "WebMediaPlaybackKind")
public typealias MediaPlaybackKind = WebMediaPlaybackKind

@available(*, deprecated, renamed: "WebMediaPlaybackPresentationMode")
public typealias MediaPlaybackPresentationMode = WebMediaPlaybackPresentationMode

@available(*, deprecated, renamed: "WebMediaPlaybackSnapshot")
public typealias MediaPlaybackSnapshot = WebMediaPlaybackSnapshot

@available(*, deprecated, renamed: "WebMediaReadyState")
public typealias MediaReadyState = WebMediaReadyState

@available(*, deprecated, renamed: "WebMediaRequestContext")
public typealias MediaRequestContext = WebMediaRequestContext

@available(*, deprecated, renamed: "WebMediaRequestContextBuilder")
public typealias MediaRequestContextBuilder = WebMediaRequestContextBuilder

@available(*, deprecated, renamed: "WebMediaResolutionMethod")
public typealias MediaResolutionMethod = WebMediaResolutionMethod

@available(*, deprecated, renamed: "WebMediaRetentionPolicy")
public typealias MediaRetentionPolicy = WebMediaRetentionPolicy

@available(*, deprecated, renamed: "WebMediaScriptConfiguration")
public typealias MediaScriptConfiguration = WebMediaScriptConfiguration

@available(*, deprecated, renamed: "WebMediaScriptEngine")
public typealias MediaScriptEngine = WebMediaScriptEngine

@available(*, deprecated, renamed: "WebMediaScriptError")
public typealias MediaScriptError = WebMediaScriptError

@available(*, deprecated, renamed: "WebMediaScriptMessage")
public typealias MediaScriptMessage = WebMediaScriptMessage

@available(*, deprecated, renamed: "WebMediaScriptMessageDecoder")
public typealias MediaScriptMessageDecoder = WebMediaScriptMessageDecoder

@available(*, deprecated, renamed: "WebMediaStreamer")
public typealias MediaStreamer = WebMediaStreamer

@available(*, deprecated, renamed: "WebMediaThumbnailLoadingPolicy")
public typealias MediaThumbnailLoadingPolicy = WebMediaThumbnailLoadingPolicy

@available(*, deprecated, renamed: "WebMediaThumbnailRequest")
public typealias MediaThumbnailRequest = WebMediaThumbnailRequest

@available(*, deprecated, renamed: "WebMediaLoader")
public typealias MediaWebLoader = WebMediaLoader

@available(*, deprecated, renamed: "WebMediaLoaderFactory")
public typealias MediaWebLoaderFactory = WebMediaLoaderFactory

@available(*, deprecated, renamed: "WebMediaMessageDecoder")
public typealias MediaWebMessageDecoder = WebMediaMessageDecoder

@available(*, deprecated, renamed: "WebMediaScriptSet")
public typealias MediaWebScriptSet = WebMediaScriptSet

@available(*, deprecated, renamed: "WebMediaScripts")
public typealias MediaWebScripts = WebMediaScripts

@available(*, deprecated, renamed: "WebMediaOfflineStorageScope")
public typealias OfflineMediaStorageScope = WebMediaOfflineStorageScope

@available(*, deprecated, renamed: "WebMediaOfflineStore")
public typealias OfflineMediaStore = WebMediaOfflineStore

@available(*, deprecated, renamed: "WebMediaOfflineStoreError")
public typealias OfflineMediaStoreError = WebMediaOfflineStoreError

@available(*, deprecated, renamed: "WebMediaArtifactDownloading")
public typealias PlaylistArtifactDownloading = WebMediaArtifactDownloading

@available(*, deprecated, renamed: "WebMediaAssetDownloader")
public typealias PlaylistAssetDownloader = WebMediaAssetDownloader

@available(*, deprecated, renamed: "WebMediaBuiltScriptSet")
public typealias PlaylistBuiltScriptSet = WebMediaBuiltScriptSet

@available(*, deprecated, renamed: "WebMediaCandidateSelector")
public typealias PlaylistCandidateSelector = WebMediaCandidateSelector

@available(*, deprecated, renamed: "WebMediaContainerKind")
public typealias PlaylistContainerKind = WebMediaContainerKind

@available(*, deprecated, renamed: "WebMediaDownloadEvent")
public typealias PlaylistDownloadEvent = WebMediaDownloadEvent

@available(*, deprecated, renamed: "WebMediaDownloadEventKind")
public typealias PlaylistDownloadEventKind = WebMediaDownloadEventKind

@available(*, deprecated, renamed: "WebMediaDownloadProgress")
public typealias PlaylistDownloadProgress = WebMediaDownloadProgress

@available(*, deprecated, renamed: "WebMediaDownloadRecord")
public typealias PlaylistDownloadRecord = WebMediaDownloadRecord

@available(*, deprecated, renamed: "WebMediaDownloadState")
public typealias PlaylistDownloadState = WebMediaDownloadState

@available(*, deprecated, renamed: "DownloadedWebMediaArtifact")
public typealias PlaylistDownloadedArtifact = DownloadedWebMediaArtifact

@available(*, deprecated, renamed: "WebMediaHLSAssetDownloader")
public typealias PlaylistHLSAssetDownloader = WebMediaHLSAssetDownloader

@available(*, deprecated, renamed: "WebMediaHLSAssetDownloading")
public typealias PlaylistHLSAssetDownloading = WebMediaHLSAssetDownloading

@available(*, deprecated, renamed: "WebMediaInfo")
public typealias PlaylistInfo = WebMediaInfo

@available(*, deprecated, renamed: "WebMediaLibrary")
public typealias PlaylistLibrary = WebMediaLibrary

@available(*, deprecated, renamed: "WebMediaKind")
public typealias PlaylistMediaKind = WebMediaKind

@available(*, deprecated, renamed: "WebMediaRequestContext")
public typealias PlaylistMediaRequestContext = WebMediaRequestContext

@available(*, deprecated, renamed: "WebMediaResolutionMethod")
public typealias PlaylistMediaResolutionMethod = WebMediaResolutionMethod

@available(*, deprecated, renamed: "WebMediaStreamer")
public typealias PlaylistMediaStreamer = WebMediaStreamer

@available(*, deprecated, renamed: "WebMediaMimeTypeDetector")
public typealias PlaylistMimeTypeDetector = WebMediaMimeTypeDetector

@available(*, deprecated, renamed: "WebMediaOfflineStore")
public typealias PlaylistOfflineMediaStore = WebMediaOfflineStore

@available(*, deprecated, renamed: "WebMediaOfflineStorageScope")
public typealias PlaylistOfflineStorageScope = WebMediaOfflineStorageScope

@available(*, deprecated, renamed: "WebMediaOfflineStoreError")
public typealias PlaylistOfflineStoreError = WebMediaOfflineStoreError

@available(*, deprecated, renamed: "WebMediaPlaybackEvent")
public typealias PlaylistPlaybackEvent = WebMediaPlaybackEvent

@available(*, deprecated, renamed: "WebMediaPlaybackEventName")
public typealias PlaylistPlaybackEventName = WebMediaPlaybackEventName

@available(*, deprecated, renamed: "WebMediaPlaybackKind")
public typealias PlaylistPlaybackKind = WebMediaPlaybackKind

@available(*, deprecated, renamed: "WebMediaPlaybackPresentationMode")
public typealias PlaylistPlaybackPresentationMode = WebMediaPlaybackPresentationMode

@available(*, deprecated, renamed: "WebMediaPlaybackSnapshot")
public typealias PlaylistPlaybackSnapshot = WebMediaPlaybackSnapshot

@available(*, deprecated, renamed: "WebMediaReadyState")
public typealias PlaylistReadyState = WebMediaReadyState

@available(*, deprecated, renamed: "WebMediaRequestContextBuilder")
public typealias PlaylistRequestContextBuilder = WebMediaRequestContextBuilder

@available(*, deprecated, renamed: "ResolvedWebMedia")
public typealias PlaylistResolvedMedia = ResolvedWebMedia

@available(*, deprecated, renamed: "ResolvedWebMediaSnapshot")
public typealias PlaylistResolvedMediaSnapshot = ResolvedWebMediaSnapshot

@available(*, deprecated, renamed: "WebMediaRetentionPolicy")
public typealias PlaylistRetentionPolicy = WebMediaRetentionPolicy

@available(*, deprecated, renamed: "WebMediaScriptConfiguration")
public typealias PlaylistScriptConfiguration = WebMediaScriptConfiguration

@available(*, deprecated, renamed: "WebMediaScriptEngine")
public typealias PlaylistScriptEngine = WebMediaScriptEngine

@available(*, deprecated, renamed: "WebMediaScriptError")
public typealias PlaylistScriptError = WebMediaScriptError

@available(*, deprecated, renamed: "WebMediaScriptMessage")
public typealias PlaylistScriptMessage = WebMediaScriptMessage

@available(*, deprecated, renamed: "WebMediaScriptMessageDecoder")
public typealias PlaylistScriptMessageDecoder = WebMediaScriptMessageDecoder

@available(*, deprecated, renamed: "StoredWebMedia")
public typealias PlaylistStoredMedia = StoredWebMedia

@available(*, deprecated, renamed: "StoredWebMediaState")
public typealias PlaylistStoredMediaState = StoredWebMediaState

@available(*, deprecated, renamed: "WebMediaThumbnailLoadingPolicy")
public typealias PlaylistThumbnailLoadingPolicy = WebMediaThumbnailLoadingPolicy

@available(*, deprecated, renamed: "WebMediaThumbnailRequest")
public typealias PlaylistThumbnailRequest = WebMediaThumbnailRequest

@available(*, deprecated, renamed: "WebMediaLoader")
public typealias PlaylistWebLoader = WebMediaLoader

@available(*, deprecated, renamed: "WebMediaLoaderFactory")
public typealias PlaylistWebLoaderFactory = WebMediaLoaderFactory

@available(*, deprecated, renamed: "WebMediaMessageDecoder")
public typealias PlaylistWebMessageDecoder = WebMediaMessageDecoder

@available(*, deprecated, renamed: "WebMediaScriptSet")
public typealias PlaylistWebScriptSet = WebMediaScriptSet

@available(*, deprecated, renamed: "WebMediaScripts")
public typealias PlaylistWebScripts = WebMediaScripts

@available(*, deprecated, renamed: "ResolvedWebMedia")
public typealias ResolvedMedia = ResolvedWebMedia

@available(*, deprecated, renamed: "ResolvedWebMediaSnapshot")
public typealias ResolvedMediaSnapshot = ResolvedWebMediaSnapshot

@available(*, deprecated, renamed: "StoredWebMedia")
public typealias StoredMedia = StoredWebMedia

@available(*, deprecated, renamed: "StoredWebMediaState")
public typealias StoredMediaState = StoredWebMediaState
